title: Mozilla Italia
email: mozillaitalia@gmail.com
description: >-
  Il sito ufficiale della comunità italiana dei volontari Mozilla che riunisce utenti e sostenitori italiani.
baseurl: ""
url: "https://mozillaitalia.org"
twitter_username: mozillaitalia
github_username:  mozillaitalia
strict_front_matter: true

keep_files:
  - img/

sass:
  style: compressed

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-watch
  - jekyll-redirect-from
  - jekyll-admin
  - jekyll-debug
